name: Deployment status

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Reason"
  push:
    branches:
      - master

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'IBM-Design/idr'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16.x

      - name: Install packages
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Build site
        run: yarn build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COS_ENDPOINT }}
          SOURCE_DIR: 'public/design/research'
          DEST_DIR: 'design/research'
