name: Deployment status

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Reason"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16.x

      - name: Install packages
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Build site
        run: yarn build

      - name: Install IBM Cloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/osx | sh

      - name: Install Cloud Foundry CLI
        run: ibmcloud cf install -v 6.51.0

      - name: Login to ibmcloud us-south
        env:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        run: ibmcloud login -a "https://cloud.ibm.com" -u apikey -p "$IBM_CLOUD_API_KEY" -o "IBMDesignOrg" -s research -r "us-south"

      - name: BlueGreen Deploy
        run: ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org && ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community

      - name: Deploy website
        run: ibmcloud cf blue-green-deploy ibm-design-research -f manifest-production.yml --delete-old-apps

      - name: Login to ibmcloud eu-de
        env:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        run: ibmcloud login -a "https://cloud.ibm.com" -u apikey -p "$IBM_CLOUD_API_KEY" -o "IBMDesignOrg" -s research -r "eu-de"

      - name: Deploy website
        run: ibmcloud cf blue-green-deploy ibm-design-research -f manifest-production.yml --delete-old-apps
        
      - name: Deploy to GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: JamesIves/github-pages-deploy-action@830e6a4f7c81743c52f3fed0ac67428feff9620a
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          # This is the branch you wish to deploy to, for example gh-pages or docs.
          branch: gh-pages
